project_id = "compa-virtual"
[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
[db]
port = 54322
major_version = 17
[db.seed]
enabled = true
sql_paths = ["./seed.sql"]
[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["compavirtual://", "http://localhost:3000"]
enable_signup = true
[auth.email]
enable_signup = true
enable_confirmations = true
[storage]
enabled = true
file_size_limit = "25MiB"
[functions.api]
verify_jwt = false
[functions.reminders]
verify_jwt = false
