// Generated by scripts/stage-shared-spaces.mjs
export const sharedSpaceModels: Record<string,number> = {
  "living-reduced.glb": require("../../web/public/selection/shared-spaces/living-reduced.glb"),
  "study-reduced.glb": require("../../web/public/selection/shared-spaces/study-reduced.glb"),
  "library-reduced.glb": require("../../web/public/selection/shared-spaces/library-reduced.glb"),
  "projects-reduced.glb": require("../../web/public/selection/shared-spaces/projects-reduced.glb"),
  "patio-reduced.glb": require("../../web/public/selection/shared-spaces/patio-reduced.glb"),
  "terrace-reduced.glb": require("../../web/public/selection/shared-spaces/terrace-reduced.glb"),
};
